# Generated by Django 5.1.4 on 2026-09-07 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pisen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.PositiveIntegerField(unique=True, verbose_name='Kód')),
                ('nazev', models.CharField(max_length=255)),
                ('interpret', models.CharField(blank=True, max_length=255)),
                ('tonina', models.CharField(blank=True, max_length=20, verbose_name='Tónina')),
                ('capo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tempo', models.PositiveSmallIntegerField(blank=True, help_text='BPM, pro vizuální metronom', null=True)),
                ('odkaz_nahravka', models.URLField(blank=True, verbose_name='Odkaz na nahrávku')),
            ],
            options={
                'verbose_name': 'Píseň',
                'verbose_name_plural': 'Písně',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='PolozkaSetlistu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradi', models.PositiveIntegerField(default=0)),
                ('pisen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zpevnik.pisen')),
            ],
            options={
                'verbose_name': 'Položka setlistu',
                'verbose_name_plural': 'Položky setlistu',
                'ordering': ['poradi'],
            },
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('pisne', models.ManyToManyField(related_name='setlisty', through='zpevnik.PolozkaSetlistu', to='zpevnik.pisen')),
            ],
            options={
                'verbose_name': 'Setlist',
                'verbose_name_plural': 'Setlisty',
                'ordering': ['-vytvoreno'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualni_pozice', models.PositiveIntegerField(default=0)),
                ('aktivni', models.BooleanField(default=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('kapelnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_jako_kapelnik', to=settings.AUTH_USER_MODEL)),
                ('setlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='zpevnik.setlist')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Session',
                'ordering': ['-vytvoreno'],
            },
        ),
        migrations.AddField(
            model_name='polozkasetlistu',
            name='setlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='zpevnik.setlist'),
        ),
        migrations.CreateModel(
            name='Slozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('rodic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podslozky', to='zpevnik.slozka')),
            ],
            options={
                'verbose_name': 'Složka',
                'verbose_name_plural': 'Složky',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='VerzePisne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_obsahu', models.CharField(choices=[('pdf', 'PDF'), ('text', 'Text')], default='pdf', max_length=10)),
                ('soubor', models.FileField(blank=True, null=True, upload_to='verze_pisni/')),
                ('stav', models.CharField(choices=[('draft', 'Koncept'), ('download', 'Stažené'), ('confirmed', 'Potvrzené'), ('handmade', 'Ručně vyrobené'), ('personal', 'Osobní')], default='draft', max_length=20)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('pisen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verze', to='zpevnik.pisen')),
                ('vlastnik', models.ForeignKey(blank=True, help_text="Povinné jen u stavu 'personal'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verze_pisni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verze písně',
                'verbose_name_plural': 'Verze písní',
                'ordering': ['-upraveno'],
            },
        ),
        migrations.CreateModel(
            name='Anotace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list, help_text='Seznam objektů: textbox, akord, tab_grid, znacka — s pozicí (x, y, strana)')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('vlastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotace', to=settings.AUTH_USER_MODEL)),
                ('pisen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotace', to='zpevnik.pisen')),
                ('verze_pisne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotace', to='zpevnik.verzepisne')),
            ],
            options={
                'verbose_name': 'Anotace',
                'verbose_name_plural': 'Anotace',
                'ordering': ['-upraveno'],
            },
        ),
        migrations.CreateModel(
            name='Zpevnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('verejny_token', models.UUIDField(blank=True, help_text='Neuhodnutelný token pro veřejný (read-only) odkaz', null=True, unique=True)),
                ('pisne', models.ManyToManyField(blank=True, related_name='zpevniky', to='zpevnik.pisen')),
                ('slozka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zpevniky', to='zpevnik.slozka')),
            ],
            options={
                'verbose_name': 'Zpěvník',
                'verbose_name_plural': 'Zpěvníky',
                'ordering': ['nazev'],
            },
        ),
    ]
