# Generated by Django 5.1.4 on 2026-09-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpevnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpevnik',
            name='verejny_token',
            field=models.CharField(blank=True, db_index=True, help_text='Neuhodnutelný token pro veřejný (read-only) odkaz', max_length=64, null=True, unique=True),
        ),
    ]
