# Generated by Django 5.1.4 on 2026-09-08 11:51

import zpevnik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpevnik', '0002_alter_zpevnik_verejny_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='verzepisne',
            name='puvodni_nazev_souboru',
            field=models.CharField(blank=True, default='', help_text='Jméno, pod kterým soubor nahrál uživatel — jen pro zobrazení, na disku se nepoužívá', max_length=255),
        ),
        migrations.AlterField(
            model_name='verzepisne',
            name='soubor',
            field=models.FileField(blank=True, null=True, upload_to=zpevnik.models.cesta_pro_soubor_verze),
        ),
    ]
