# Generated by Django 5.1.4 on 2026-09-18 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpevnik', '0003_verzepisne_puvodni_nazev_souboru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anotace',
            constraint=models.UniqueConstraint(fields=('verze_pisne', 'vlastnik'), name='unikatni_anotace_verze_vlastnik'),
        ),
    ]
