# Generated by Django 5.1.4, ručně rozdělen na tři kroky (0005–0007) místo
# jednoho — Django by jinak smazal Pisen.kod DŘÍV, než by šel zkopírovat do
# nové tabulky. Krok 1/3: jen PŘIDAT novou tabulku, nic starého se ještě
# nedotýká.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zpevnik", "0004_anotace_unikatni_anotace_verze_vlastnik"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolozkaZpevniku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.PositiveIntegerField(verbose_name="Kód")),
                (
                    "pisen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polozky_zpevniku",
                        to="zpevnik.pisen",
                    ),
                ),
                (
                    "zpevnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polozky",
                        to="zpevnik.zpevnik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Položka zpěvníku",
                "verbose_name_plural": "Položky zpěvníku",
                "ordering": ["kod"],
            },
        ),
        migrations.AddConstraint(
            model_name="polozkazpevniku",
            constraint=models.UniqueConstraint(
                fields=("zpevnik", "kod"), name="unikatni_kod_ve_zpevniku"
            ),
        ),
        migrations.AddConstraint(
            model_name="polozkazpevniku",
            constraint=models.UniqueConstraint(
                fields=("zpevnik", "pisen"), name="pisen_jednou_ve_zpevniku"
            ),
        ),
    ]
