# Generated by Django 5.1.4 on 2026-09-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpevnik', '0007_pisen_bez_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='verzepisne',
            name='akordy',
            field=models.JSONField(blank=True, help_text='Zdrojová data akordového zápisu (jen zdroj=akordy) — viz PC_zpevnik_akordovy_zapis.md', null=True),
        ),
        migrations.AddField(
            model_name='verzepisne',
            name='zdroj',
            field=models.CharField(choices=[('pdf', 'Nahrané PDF'), ('akordy', 'Akordový zápis')], default='pdf', max_length=10),
        ),
    ]
