# Generated by Django 5.1.4 on 2026-09-22, ručně rozdělené (viz 0010, 0011) —
# pole se přidává nejdřív bez constraintu, ať jde v 0010 doplnit existující
# řádky RunPythonem dřív, než 0011 zapne unikátnost.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpevnik', '0008_verzepisne_akordy_verzepisne_zdroj'),
    ]

    operations = [
        migrations.AddField(
            model_name='verzepisne',
            name='cislo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Číslo verze'),
        ),
    ]
